// Package main provides the administrative console for the Onyx Security Appliance.
// It serves as the primary interface for managing local and remote Onyx instances
// through a Terminal User Interface (TUI).
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"onyx/internal/config"
	"onyx/internal/ui"

	"github.com/spf13/cobra"
)

// version defines the current build version of the admin tool.
var version = "v0.1.6"

// rootCmd represents the base command when called without any subcommands.
var rootCmd = &cobra.Command{
	Use:   "onyx-admin",
	Short: "Onyx Admin: The management console for the Onyx Security Appliance.",
	Long: `Onyx Admin is a specialized TUI tool designed to monitor and manage 
Onyx security engines. It supports local management via unix sockets 
and remote management via mTLS-secured connections.`,
}

// statusCmd represents the command to launch the interactive dashboard.
var statusCmd = &cobra.Command{
	Use:   "status",
	Short: "Launch the interactive status dashboard",
	Run: func(cmd *cobra.Command, args []string) {
		home, _ := os.UserHomeDir()
		configPath := filepath.Join(home, ".config", "onyx", "servers.toml")

		conf, err := config.LoadConfig(configPath)
		if err != nil {
			fmt.Printf("Note: Running in local mode (%v)\n", err)
		}

		if err := ui.StartTUI(version, conf); err != nil {
			fmt.Printf("Error launching console: %v\n", err)
			os.Exit(1)
		}
	},
}

// pairCmd represents the command to link this admin tool with a remote Onyx engine.
// It requires a target IP and a one-time pairing token generated by the server.
var pairCmd = &cobra.Command{
	Use:   "pair [ip-address]",
	Short: "Pair this console with a remote Onyx Security Engine",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		targetIP := args[0]
		token, _ := cmd.Flags().GetString("token")

		if token == "" {
			fmt.Println("Error: A pairing --token is required for initial setup.")
			fmt.Println("Check the Onyx service logs on the target server for the pairing token.")
			os.Exit(1)
		}

		fmt.Printf("Initiating secure pairing with %s...\n", targetIP)
		// TODO: Implement the cryptographic handshake and TOML update logic.
	},
}

// main initializes the command-line interface and executes the root command.
func main() {
	// Register flags for the pair command
	pairCmd.Flags().StringP("token", "t", "", "One-time pairing token from the server logs")

	// Add subcommands to the root
	rootCmd.AddCommand(statusCmd)
	rootCmd.AddCommand(pairCmd)

	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
